language: java
jdk:
  - openjdk8

script: ./gradlew build -PoverrideVersion=${BUILDTAG} --continue

sudo: true

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - build/distributions/blitz-remote-${BUILDTAG}.zip
    - build/libs/blitz-remote-${BUILDTAG}.jar
  skip_cleanup: true
  on:
    tags: true
  overwrite: true
