language: java
jdk:
  - openjdk8

before_script: env

script: ./gradlew build -PoverrideVersion=${BUILDTAG} --continue

sudo: true

after_script: find build/distributions; find build/libs

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - "build/distributions/blitz-remote-${BUILDTAG}.zip"
    - "build/libs/blitz-remote-${BUILDTAG}.jar"
  skip_cleanup: true
  on:
    tags: true
  overwrite: true
